version=2.9.0-SNAPSHOT
buildNumber=290010
group=com.incquerylabs.v4md
viatraVersion=2.9.1
deployUrl = "build/maven-repository"
// Only used for test cases
xtextVersion=2.35.0
mdVersion=2024x

magicdrawBinaryRepository=https://build.incquerylabs.com/nexus/repository/nomagic-binaries/
deployReleaseUrl=https://build.incquerylabs.com/nexus/repository/v4md-releases/
deploySnapshotUrl=https://build.incquerylabs.com/nexus/repository/v4md-snapshots/
